name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Libraries
        run: "vcpkg install --triplet=${{env.VCPKG_DEFAULT_TRIPLET}}"
