name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
